import "./globals.css";
import type { Metadata } from "next";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import { FavoriteProvider } from "./context/FavoriteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sngular Prueba Front App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <FavoriteProvider>
          <Header/>
          <main style={{ flexGrow: 9, width: '100%' }}>
            {children}
          </main>
          <Footer/>
        </FavoriteProvider>
      </body>
    </html>
  );
}
